### ISSUE TITLE
Uncertainties are lost for binned Rainbow

### ISSUE THREAD

**Issue by catrionamurray** [zkbt/chromatic#36]
When a Rainbow is binned we lose the uncertainties, either when using linear bins or predefined bin centres.

**Comment by catrionamurray** [comment]
Actually not totally lost - there's no 'uncertainty' quantity anymore but there's an array of the right size under 'flux_error', but it's full of nans.

**Comment by zkbt** [comment]
Oops! I found this in the binning functions:
```
# TODO (add more careful treatment of uncertainty + DQ)
```
I think I was putting it off because I wanted to do both uncertainties and masking bad data at the same time before going into bins, but it's actually not that bad to do the uncertainties. I'll try to get this fixed this morning before meetings start at 10am.

**Comment by zkbt** [comment]
Blerg. Almost but didn't quite finish before meetings started. Hope to get to it this afternoon!

**Comment by zkbt** [comment]
That test also highlights that we should probably throw some kind of a warning if folks try to bin to a higher resolution than the starting dataset (e.g. dw=0.01 microns). The code *will* try to split one bin into many, but it will do so quietly, and that's not necessarily what everyone will want.

**Comment by zkbt** [comment]
@catrionamurray , could you please check to see that v0.0.10 works with the NIRCam data? I only tested it on my very cartoon simulated Rainbow, and it'd be good to make sure it works OK even with real data.

**Comment by catrionamurray** [comment]
I'm afraid I'm getting all NaNs for the NIRCam data

**Comment by zkbt** [comment]
It looks like the NIRCam data had, I think, some points with uncertainty of `0` but flux that wasn't `nan`. These were sneaking through the data quality checks and so some divide by zeros were making everything blow up. I think I fixed this in v0.0.11 now? (Technically we could have been iterating on that development branch itself, but I merged it into `main` because I knew it was definitely at least better than what was there before.)

**Comment by zkbt** [comment]
Could you please try (yet) again with the NIRCam dataset, @catrionamurray ? Fingers crossed I got it this time!

**Comment by catrionamurray** [comment]
I'm not sure v0.0.11 is available on pip?

**Comment by zkbt** [comment]
I *think* this is mostly fixed now. I'm going to close it for the time being, but if we need to reopen it or write a new related one, we can.
